#!/usr/bin/env tsx
/**
 * Generates the README's service parity table from the shared registry, so the
 * table can never drift from the console's actual navigation. Run
 * `pnpm gen:parity` to update it and `pnpm gen:parity:check` to verify it in CI
 * without writing.
 *
 * The table is emitted in Prettier's markdown-table format (columns padded to
 * their widest cell), so `pnpm lint:format` stays green right after a
 * regeneration.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICE_CATALOG, SERVICE_CATEGORIES } from '../packages/shared/src/index.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const README_PATH = path.join(REPO_ROOT, 'README.md');

const BEGIN = '<!-- BEGIN PARITY TABLE';
const END = '<!-- END PARITY TABLE -->';

const SUPPORT_LABEL: Readonly<Record<string, string>> = {
  dedicated: 'dedicated',
  browser: 'generic browser',
  planned: 'planned',
};

interface TableRow {
  cells: readonly string[];
}

function renderTable(header: readonly string[], rows: readonly TableRow[]): string {
  const widths = header.map((cell, index) =>
    Math.max(cell.length, 3, ...rows.map((row) => (row.cells[index] ?? '').length)),
  );
  const renderRow = (cells: readonly string[]): string =>
    `| ${cells.map((cell, index) => cell.padEnd(widths[index] ?? 0)).join(' | ')} |`;

  return [
    renderRow(header),
    renderRow(widths.map((width) => '-'.repeat(width))),
    ...rows.map((row) => renderRow(row.cells)),
  ].join('\n');
}

function buildSection(): string {
  const rows: TableRow[] = [];
  for (const category of SERVICE_CATEGORIES) {
    const services = SERVICE_CATALOG.filter((service) => service.category === category).sort(
      (left, right) => left.displayName.localeCompare(right.displayName, 'en'),
    );
    for (const service of services) {
      rows.push({
        cells: [
          category,
          service.displayName,
          `\`${service.id}\``,
          SUPPORT_LABEL[service.parityLevel] ?? service.parityLevel,
        ],
      });
    }
  }

  const counts = {
    dedicated: SERVICE_CATALOG.filter((service) => service.parityLevel === 'dedicated').length,
    browser: SERVICE_CATALOG.filter((service) => service.parityLevel === 'browser').length,
    planned: SERVICE_CATALOG.filter((service) => service.parityLevel === 'planned').length,
  };

  return [
    `${BEGIN} (generated by \`pnpm gen:parity\` — do not edit by hand) -->`,
    '',
    `${SERVICE_CATALOG.length} services across the eleven console categories: ` +
      `**${counts.dedicated} dedicated**, **${counts.browser} generic browser**, ` +
      `**${counts.planned} planned**.`,
    '',
    renderTable(['Category', 'Service', 'Console id', 'LocalDeck support'], rows),
    '',
    END,
  ].join('\n');
}

/** Prettier may adjust padding, so compare without space runs. */
function normalize(markdown: string): string {
  return markdown
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function main(): void {
  const check = process.argv.includes('--check');
  const readme = readFileSync(README_PATH, 'utf8');
  const beginIndex = readme.indexOf(BEGIN);
  const endIndex = readme.indexOf(END);

  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    console.error('README.md is missing the generated parity table markers.');
    process.exitCode = 1;
    return;
  }

  const current = readme.slice(beginIndex, endIndex + END.length);
  const next = buildSection();

  if (normalize(current) === normalize(next)) {
    console.log('README parity table is up to date.');
    return;
  }

  if (check) {
    console.error('README parity table is stale. Run `pnpm gen:parity` and commit the result.');
    process.exitCode = 1;
    return;
  }

  writeFileSync(
    README_PATH,
    `${readme.slice(0, beginIndex)}${next}${readme.slice(endIndex + END.length)}`,
    'utf8',
  );
  console.log('README parity table updated.');
}

main();
