import type { ServiceDescriptor } from './types.js';

/** Analytics services, in console order. */
export const ANALYTICS_SERVICES = [
  {
    id: 'athena',
    displayName: 'Athena',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-athena',
    iconKey: 'athena',
    operations: [
      'ListWorkGroups',
      'StartQueryExecution',
      'GetQueryExecution',
      'ListDataCatalogs',
      'GetWorkGroup',
      'DeleteWorkGroup',
    ],
    parityLevel: 'browser',
    summary: 'SQL workgroups, query executions and data catalogs.',
    browser: {
      list: { operation: 'ListWorkGroups', resultPath: 'WorkGroups', idField: 'Name' },
      describe: { operation: 'GetWorkGroup', idParam: 'WorkGroup' },
      delete: { operation: 'DeleteWorkGroup', idParam: 'WorkGroup' },
    },
  },
  {
    id: 'glue',
    displayName: 'Glue',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-glue',
    iconKey: 'glue',
    operations: [
      'GetDatabases',
      'GetTables',
      'GetJobs',
      'StartJobRun',
      'GetCrawlers',
      'GetDatabase',
      'DeleteDatabase',
    ],
    parityLevel: 'browser',
    summary: 'Data catalog databases, tables, crawlers and jobs.',
    browser: {
      list: { operation: 'GetDatabases', resultPath: 'DatabaseList', idField: 'Name' },
      describe: { operation: 'GetDatabase', idParam: 'Name' },
      delete: { operation: 'DeleteDatabase', idParam: 'Name' },
    },
  },
  {
    id: 'emr',
    displayName: 'EMR',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-emr',
    iconKey: 'emr',
    operations: [
      'ListClusters',
      'DescribeCluster',
      'RunJobFlow',
      'ListInstanceGroups',
      'TerminateJobFlows',
    ],
    parityLevel: 'browser',
    summary: 'Apache Spark and Hadoop clusters on EC2.',
    healthKeys: ['emr-serverless'],
    browser: {
      list: { operation: 'ListClusters', resultPath: 'Clusters', idField: 'Id', nameField: 'Name' },
      describe: { operation: 'DescribeCluster', idParam: 'ClusterId' },
      delete: { operation: 'TerminateJobFlows', idParam: 'JobFlowIds', idParamIsArray: true },
    },
  },
  {
    id: 'kinesis',
    displayName: 'Kinesis',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-kinesis',
    iconKey: 'kinesis',
    operations: [
      'ListStreams',
      'CreateStream',
      'DescribeStream',
      'PutRecord',
      'GetShardIterator',
      'GetRecords',
      'DeleteStream',
    ],
    parityLevel: 'browser',
    summary: 'Data streams, shards, records and stream consumers.',
    browser: {
      list: { operation: 'ListStreams', resultPath: 'StreamNames' },
      describe: { operation: 'DescribeStream', idParam: 'StreamName' },
      delete: { operation: 'DeleteStream', idParam: 'StreamName' },
    },
  },
  {
    id: 'kinesisanalyticsv2',
    displayName: 'Managed Service for Apache Flink',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-kinesis-analytics-v2',
    iconKey: 'kinesis',
    operations: [
      'ListApplications',
      'DescribeApplication',
      'StartApplication',
      'StopApplication',
      'DeleteApplication',
    ],
    parityLevel: 'browser',
    summary: 'Streaming applications running Apache Flink.',
    browser: {
      list: {
        operation: 'ListApplications',
        resultPath: 'ApplicationSummaries',
        idField: 'ApplicationName',
      },
      describe: { operation: 'DescribeApplication', idParam: 'ApplicationName' },
    },
  },
  {
    id: 'firehose',
    displayName: 'Data Firehose',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-firehose',
    iconKey: 'firehose',
    operations: [
      'ListDeliveryStreams',
      'CreateDeliveryStream',
      'DescribeDeliveryStream',
      'PutRecord',
      'DeleteDeliveryStream',
    ],
    parityLevel: 'browser',
    summary: 'Delivery streams into S3, Redshift, OpenSearch and Splunk.',
    browser: {
      list: { operation: 'ListDeliveryStreams', resultPath: 'DeliveryStreamNames' },
      describe: { operation: 'DescribeDeliveryStream', idParam: 'DeliveryStreamName' },
      delete: { operation: 'DeleteDeliveryStream', idParam: 'DeliveryStreamName' },
    },
  },
  {
    id: 'opensearch',
    displayName: 'OpenSearch Service',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-opensearch',
    iconKey: 'opensearch',
    operations: ['ListDomainNames', 'DescribeDomain', 'CreateDomain', 'DeleteDomain'],
    parityLevel: 'browser',
    summary: 'Search and log analytics domains and clusters.',
    healthKeys: ['es'],
    browser: {
      list: {
        operation: 'ListDomainNames',
        resultPath: 'DomainNames',
        idField: 'DomainName',
      },
      describe: { operation: 'DescribeDomain', idParam: 'DomainName' },
      delete: { operation: 'DeleteDomain', idParam: 'DomainName' },
    },
  },
  {
    id: 'lakeformation',
    displayName: 'Lake Formation',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-lakeformation',
    iconKey: 'lakeformation',
    operations: ['ListResources', 'GetEffectivePermissionsForPath', 'ListDataCellsFilter'],
    parityLevel: 'planned',
    summary: 'Fine-grained data lake permissions.',
  },
  {
    id: 'quicksight',
    displayName: 'QuickSight',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-quicksight',
    iconKey: 'quicksight',
    operations: ['ListDashboards', 'ListDataSets', 'ListDataSources'],
    parityLevel: 'planned',
    summary: 'Business intelligence dashboards and datasets.',
  },
  {
    id: 'kafka',
    displayName: 'Managed Streaming for Kafka',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-kafka',
    iconKey: 'kafka',
    operations: ['ListClustersV2', 'DescribeClusterV2', 'CreateClusterV2', 'DeleteCluster'],
    parityLevel: 'browser',
    summary: 'MSK clusters with broker nodes and configurations.',
    browser: {
      list: {
        operation: 'ListClustersV2',
        resultPath: 'ClusterInfoList',
        idField: 'ClusterArn',
        nameField: 'ClusterName',
      },
      describe: { operation: 'DescribeClusterV2', idParam: 'ClusterArn' },
      delete: { operation: 'DeleteCluster', idParam: 'ClusterArn' },
    },
  },
  {
    id: 'mwaa',
    displayName: 'Managed Workflows for Apache Airflow',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-mwaa',
    iconKey: 'mwaa',
    operations: ['ListEnvironments', 'GetEnvironment', 'CreateEnvironment', 'DeleteEnvironment'],
    parityLevel: 'browser',
    summary: 'Airflow environments and their DAG runs.',
    browser: {
      list: { operation: 'ListEnvironments', resultPath: 'Environments' },
      describe: { operation: 'GetEnvironment', idParam: 'Name' },
      delete: { operation: 'DeleteEnvironment', idParam: 'Name' },
    },
  },
  {
    id: 'mediaconvert',
    displayName: 'Elemental MediaConvert',
    category: 'Analytics',
    sdkPackage: '@aws-sdk/client-mediaconvert',
    iconKey: 'mediaconvert',
    operations: ['ListQueues', 'GetQueue', 'CreateQueue', 'DeleteQueue'],
    parityLevel: 'browser',
    summary: 'File-based video transcoding queues and jobs.',
    browser: {
      list: { operation: 'ListQueues', resultPath: 'Queues', idField: 'Name' },
      describe: { operation: 'GetQueue', idParam: 'Name' },
      delete: { operation: 'DeleteQueue', idParam: 'Name' },
    },
  },
] as const satisfies readonly ServiceDescriptor[];
