import type { ServiceDescriptor } from './types.js';

/** Compute services, in console order. */
export const COMPUTE_SERVICES = [
  {
    id: 'ec2',
    displayName: 'EC2',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-ec2',
    iconKey: 'ec2',
    operations: [
      // Instances
      'DescribeInstances',
      'RunInstances',
      'StartInstances',
      'StopInstances',
      'RebootInstances',
      'TerminateInstances',
      // Images and instance types
      'DescribeImages',
      'DescribeInstanceTypes',
      // Key pairs
      'DescribeKeyPairs',
      'CreateKeyPair',
      'DeleteKeyPair',
      // Security groups
      'DescribeSecurityGroups',
      'CreateSecurityGroup',
      'AuthorizeSecurityGroupIngress',
      'RevokeSecurityGroupIngress',
      'DeleteSecurityGroup',
      // Volumes
      'DescribeVolumes',
      'CreateVolume',
      'AttachVolume',
      'DeleteVolume',
      // Tags
      'CreateTags',
      'DeleteTags',
      // Networking
      'DescribeVpcs',
      'DescribeSubnets',
      'DescribeAvailabilityZones',
    ],
    parityLevel: 'dedicated',
    summary: 'Virtual machines, security groups, VPCs, subnets and AMIs.',
  },
  {
    id: 'lambda',
    displayName: 'Lambda',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-lambda',
    iconKey: 'lambda',
    operations: [
      'ListFunctions',
      'GetFunction',
      'CreateFunction',
      'UpdateFunctionCode',
      'UpdateFunctionConfiguration',
      'Invoke',
      'DeleteFunction',
    ],
    parityLevel: 'browser',
    summary: 'Serverless functions, code, environment and invocations.',
    browser: {
      list: { operation: 'ListFunctions', resultPath: 'Functions', idField: 'FunctionName' },
      describe: { operation: 'GetFunction', idParam: 'FunctionName' },
      delete: { operation: 'DeleteFunction', idParam: 'FunctionName' },
    },
  },
  {
    id: 'autoscaling',
    displayName: 'EC2 Auto Scaling',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-auto-scaling',
    iconKey: 'autoscaling',
    operations: [
      'DescribeAutoScalingGroups',
      'CreateAutoScalingGroup',
      'UpdateAutoScalingGroup',
      'DeleteAutoScalingGroup',
      'DescribeScalingActivities',
      'DescribeLaunchConfigurations',
    ],
    parityLevel: 'browser',
    summary: 'Automatic scaling of EC2 capacity from launch templates.',
    browser: {
      list: {
        operation: 'DescribeAutoScalingGroups',
        resultPath: 'AutoScalingGroups',
        idField: 'AutoScalingGroupName',
      },
      describe: {
        operation: 'DescribeAutoScalingGroups',
        idParam: 'AutoScalingGroupNames',
        idParamIsArray: true,
      },
      delete: { operation: 'DeleteAutoScalingGroup', idParam: 'AutoScalingGroupName' },
    },
  },
  {
    id: 'batch',
    displayName: 'Batch',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-batch',
    iconKey: 'batch',
    operations: [
      'DescribeJobQueues',
      'DescribeJobs',
      'SubmitJob',
      'CancelJob',
      'DescribeComputeEnvironments',
      'DeleteJobQueue',
    ],
    parityLevel: 'browser',
    summary: 'Batch computing jobs and queues on managed compute.',
    browser: {
      list: {
        operation: 'DescribeJobQueues',
        resultPath: 'jobQueues',
        idField: 'jobQueueArn',
        nameField: 'jobQueueName',
      },
      delete: { operation: 'DeleteJobQueue', idParam: 'jobQueue' },
    },
  },
  {
    id: 'elasticbeanstalk',
    displayName: 'Elastic Beanstalk',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-elastic-beanstalk',
    iconKey: 'elasticbeanstalk',
    operations: [
      'DescribeApplications',
      'CreateApplication',
      'DescribeEnvironments',
      'DescribeEvents',
      'DeleteApplication',
    ],
    parityLevel: 'browser',
    summary: 'Application environments provisioned from platform versions.',
    browser: {
      list: {
        operation: 'DescribeApplications',
        resultPath: 'Applications',
        idField: 'ApplicationName',
      },
      describe: {
        operation: 'DescribeApplications',
        idParam: 'ApplicationNames',
        idParamIsArray: true,
      },
      delete: { operation: 'DeleteApplication', idParam: 'ApplicationName' },
    },
  },
  {
    id: 'application-autoscaling',
    displayName: 'Application Auto Scaling',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-application-auto-scaling',
    iconKey: 'autoscaling',
    operations: [
      'DescribeScalableTargets',
      'RegisterScalableTarget',
      'DeregisterScalableTarget',
      'DescribeScalingPolicies',
      'PutScalingPolicy',
      'DeleteScalingPolicy',
    ],
    parityLevel: 'planned',
    summary: 'Scaling policies for ECS, DynamoDB, Lambda and other targets.',
  },
  {
    id: 'lightsail',
    displayName: 'Lightsail',
    category: 'Compute',
    sdkPackage: '@aws-sdk/client-lightsail',
    iconKey: 'lightsail',
    operations: ['GetInstances', 'CreateInstances', 'StartInstance', 'StopInstance'],
    parityLevel: 'planned',
    summary: 'Simplified virtual private servers with bundled networking.',
  },
] as const satisfies readonly ServiceDescriptor[];
