import type { ServiceDescriptor } from './types.js';

/** Database services, in console order. */
export const DATABASE_SERVICES = [
  {
    id: 'dynamodb',
    displayName: 'DynamoDB',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-dynamodb',
    iconKey: 'dynamodb',
    operations: [
      'ListTables',
      'DescribeTable',
      'CreateTable',
      'DeleteTable',
      'Scan',
      'Query',
      'PutItem',
      'GetItem',
    ],
    parityLevel: 'browser',
    summary: 'Tables, items, key schema, indexes and streams.',
    browser: {
      list: { operation: 'ListTables', resultPath: 'TableNames' },
      describe: { operation: 'DescribeTable', idParam: 'TableName' },
      delete: { operation: 'DeleteTable', idParam: 'TableName' },
    },
  },
  {
    id: 'dynamodbstreams',
    displayName: 'DynamoDB Streams',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-dynamodb-streams',
    iconKey: 'dynamodb',
    operations: ['ListStreams', 'DescribeStream', 'GetShardIterator', 'GetRecords'],
    parityLevel: 'browser',
    summary: 'Change streams with shards and records for DynamoDB tables.',
    browser: {
      list: {
        operation: 'ListStreams',
        resultPath: 'Streams',
        idField: 'StreamArn',
        nameField: 'TableName',
      },
      describe: { operation: 'DescribeStream', idParam: 'StreamArn' },
    },
  },
  {
    id: 'rds',
    displayName: 'RDS',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-rds',
    iconKey: 'rds',
    operations: [
      'DescribeDBInstances',
      'CreateDBInstance',
      'DeleteDBInstance',
      'DescribeDBClusters',
      'DescribeDBSubnetGroups',
    ],
    parityLevel: 'browser',
    summary: 'Relational database instances, clusters and subnet groups.',
    healthKeys: ['rds-data'],
    browser: {
      list: {
        operation: 'DescribeDBInstances',
        resultPath: 'DBInstances',
        idField: 'DBInstanceIdentifier',
      },
      describe: { operation: 'DescribeDBInstances', idParam: 'DBInstanceIdentifier' },
      delete: { operation: 'DeleteDBInstance', idParam: 'DBInstanceIdentifier' },
    },
  },
  {
    id: 'dsql',
    displayName: 'Aurora DSQL',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-dsql',
    iconKey: 'dsql',
    operations: ['ListClusters', 'GetCluster', 'CreateCluster', 'DeleteCluster'],
    parityLevel: 'browser',
    summary: 'Serverless, distributed SQL clusters.',
    browser: {
      list: {
        operation: 'ListClusters',
        resultPath: 'clusters',
        idField: 'identifier',
        nameField: 'identifier',
      },
      describe: { operation: 'GetCluster', idParam: 'identifier' },
      delete: { operation: 'DeleteCluster', idParam: 'identifier' },
    },
  },
  {
    id: 'docdb',
    displayName: 'DocumentDB',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-docdb',
    iconKey: 'docdb',
    operations: ['DescribeDBClusters', 'CreateDBCluster', 'DeleteDBCluster'],
    parityLevel: 'browser',
    summary: 'MongoDB-compatible document database clusters.',
    browser: {
      list: {
        operation: 'DescribeDBClusters',
        resultPath: 'DBClusters',
        idField: 'DBClusterIdentifier',
      },
      describe: { operation: 'DescribeDBClusters', idParam: 'DBClusterIdentifier' },
      delete: { operation: 'DeleteDBCluster', idParam: 'DBClusterIdentifier' },
    },
  },
  {
    id: 'elasticache',
    displayName: 'ElastiCache',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-elasticache',
    iconKey: 'elasticache',
    operations: [
      'DescribeCacheClusters',
      'CreateCacheCluster',
      'DeleteCacheCluster',
      'DescribeReplicationGroups',
    ],
    parityLevel: 'browser',
    summary: 'Valkey, Redis and Memcached clusters and replication groups.',
    browser: {
      list: {
        operation: 'DescribeCacheClusters',
        resultPath: 'CacheClusters',
        idField: 'CacheClusterId',
      },
      describe: { operation: 'DescribeCacheClusters', idParam: 'CacheClusterId' },
      delete: { operation: 'DeleteCacheCluster', idParam: 'CacheClusterId' },
    },
  },
  {
    id: 'memorydb',
    displayName: 'MemoryDB',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-memorydb',
    iconKey: 'memorydb',
    operations: ['DescribeClusters', 'CreateCluster', 'DeleteCluster'],
    parityLevel: 'browser',
    summary: 'Durable in-memory database clusters.',
    browser: {
      list: { operation: 'DescribeClusters', resultPath: 'Clusters', idField: 'Name' },
      describe: { operation: 'DescribeClusters', idParam: 'ClusterName' },
      delete: { operation: 'DeleteCluster', idParam: 'ClusterName' },
    },
  },
  {
    id: 'neptune',
    displayName: 'Neptune',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-neptune',
    iconKey: 'neptune',
    operations: ['DescribeDBClusters', 'CreateDBCluster', 'DeleteDBCluster'],
    parityLevel: 'browser',
    summary: 'Graph database clusters and instances.',
    browser: {
      list: {
        operation: 'DescribeDBClusters',
        resultPath: 'DBClusters',
        idField: 'DBClusterIdentifier',
      },
      describe: { operation: 'DescribeDBClusters', idParam: 'DBClusterIdentifier' },
      delete: { operation: 'DeleteDBCluster', idParam: 'DBClusterIdentifier' },
    },
  },
  {
    id: 'redshift',
    displayName: 'Redshift',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-redshift',
    iconKey: 'redshift',
    operations: ['DescribeClusters', 'CreateCluster', 'DeleteCluster', 'DescribeClusterSnapshots'],
    parityLevel: 'browser',
    summary: 'Analytics warehouse clusters and snapshots.',
    healthKeys: ['redshift-data'],
    browser: {
      list: {
        operation: 'DescribeClusters',
        resultPath: 'Clusters',
        idField: 'ClusterIdentifier',
      },
      describe: { operation: 'DescribeClusters', idParam: 'ClusterIdentifier' },
      delete: { operation: 'DeleteCluster', idParam: 'ClusterIdentifier' },
    },
  },
  {
    id: 'timestream',
    displayName: 'Timestream',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-timestream-write',
    iconKey: 'timestream',
    operations: [
      'ListDatabases',
      'ListTables',
      'DescribeEndpoints',
      'CreateDatabase',
      'DescribeDatabase',
      'DeleteDatabase',
    ],
    parityLevel: 'browser',
    summary: 'Time-series databases and tables.',
    healthKeys: ['timestream-write', 'timestream-query'],
    browser: {
      list: {
        operation: 'ListDatabases',
        resultPath: 'Databases',
        idField: 'DatabaseName',
      },
      describe: { operation: 'DescribeDatabase', idParam: 'DatabaseName' },
      delete: { operation: 'DeleteDatabase', idParam: 'DatabaseName' },
    },
  },
  {
    id: 'dms',
    displayName: 'Database Migration Service',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-dms',
    iconKey: 'dms',
    operations: [
      'DescribeReplicationInstances',
      'DescribeReplicationTasks',
      'DescribeEndpoints',
      'DeleteReplicationInstance',
    ],
    parityLevel: 'browser',
    summary: 'Migration endpoints, replication instances and tasks.',
    browser: {
      list: {
        operation: 'DescribeReplicationInstances',
        resultPath: 'ReplicationInstances',
        idField: 'ReplicationInstanceArn',
        nameField: 'ReplicationInstanceIdentifier',
      },
      delete: { operation: 'DeleteReplicationInstance', idParam: 'ReplicationInstanceArn' },
    },
  },
  {
    id: 'keyspaces',
    displayName: 'Keyspaces',
    category: 'Database',
    sdkPackage: '@aws-sdk/client-keyspaces',
    iconKey: 'keyspaces',
    operations: ['ListKeyspaces', 'GetKeyspace', 'ListTables'],
    parityLevel: 'planned',
    summary: 'Apache Cassandra-compatible keyspaces.',
  },
] as const satisfies readonly ServiceDescriptor[];
