import type { ServiceDescriptor } from './types.js';

/** Developer tools services, in console order. */
export const DEVELOPER_TOOLS_SERVICES = [
  {
    id: 'codecommit',
    displayName: 'CodeCommit',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codecommit',
    iconKey: 'codecommit',
    operations: [
      'ListRepositories',
      'GetRepository',
      'CreateRepository',
      'ListBranches',
      'DeleteRepository',
    ],
    parityLevel: 'browser',
    summary: 'Git repositories, branches and commits.',
    browser: {
      list: {
        operation: 'ListRepositories',
        resultPath: 'repositories',
        idField: 'repositoryName',
      },
      describe: { operation: 'GetRepository', idParam: 'repositoryName' },
      delete: { operation: 'DeleteRepository', idParam: 'repositoryName' },
    },
  },
  {
    id: 'codebuild',
    displayName: 'CodeBuild',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codebuild',
    iconKey: 'codebuild',
    operations: [
      'ListProjects',
      'BatchGetProjects',
      'StartBuild',
      'ListBuildsForProject',
      'DeleteProject',
    ],
    parityLevel: 'browser',
    summary: 'Build projects, builds and build logs.',
    browser: {
      list: { operation: 'ListProjects', resultPath: 'projects' },
      describe: { operation: 'BatchGetProjects', idParam: 'names', idParamIsArray: true },
      delete: { operation: 'DeleteProject', idParam: 'name' },
    },
  },
  {
    id: 'codedeploy',
    displayName: 'CodeDeploy',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codedeploy',
    iconKey: 'codedeploy',
    operations: [
      'ListApplications',
      'ListDeployments',
      'GetDeployment',
      'CreateDeployment',
      'GetApplication',
      'DeleteApplication',
    ],
    parityLevel: 'browser',
    summary: 'Deployment applications, groups and revisions.',
    browser: {
      list: { operation: 'ListApplications', resultPath: 'applications' },
      describe: { operation: 'GetApplication', idParam: 'applicationName' },
      delete: { operation: 'DeleteApplication', idParam: 'applicationName' },
    },
  },
  {
    id: 'codepipeline',
    displayName: 'CodePipeline',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codepipeline',
    iconKey: 'codepipeline',
    operations: [
      'ListPipelines',
      'GetPipelineState',
      'StartPipelineExecution',
      'GetPipeline',
      'DeletePipeline',
    ],
    parityLevel: 'browser',
    summary: 'Delivery pipelines, stages and executions.',
    browser: {
      list: { operation: 'ListPipelines', resultPath: 'pipelines', idField: 'name' },
      describe: { operation: 'GetPipeline', idParam: 'name' },
      delete: { operation: 'DeletePipeline', idParam: 'name' },
    },
  },
  {
    id: 'codeartifact',
    displayName: 'CodeArtifact',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codeartifact',
    iconKey: 'codeartifact',
    operations: [
      'ListDomains',
      'ListRepositories',
      'ListPackages',
      'DescribeDomain',
      'DeleteDomain',
    ],
    parityLevel: 'browser',
    summary: 'Package repositories and upstream connections.',
    browser: {
      list: { operation: 'ListDomains', resultPath: 'domains', idField: 'arn', nameField: 'name' },
      describe: { operation: 'DescribeDomain', idParam: 'domain' },
      delete: { operation: 'DeleteDomain', idParam: 'domain' },
    },
  },
  {
    id: 'codeconnections',
    displayName: 'CodeConnections',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-codeconnections',
    iconKey: 'codecommit',
    operations: ['ListConnections', 'GetConnection', 'ListHosts', 'DeleteConnection'],
    parityLevel: 'browser',
    summary: 'Third-party Git connections used by pipelines.',
    healthKeys: ['codestar-connections'],
    browser: {
      list: {
        operation: 'ListConnections',
        resultPath: 'Connections',
        idField: 'ConnectionArn',
        nameField: 'ConnectionName',
      },
      describe: { operation: 'GetConnection', idParam: 'ConnectionArn' },
      delete: { operation: 'DeleteConnection', idParam: 'ConnectionArn' },
    },
  },
  {
    id: 'xray',
    displayName: 'X-Ray',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-xray',
    iconKey: 'xray',
    operations: [
      'GetServiceGraph',
      'GetTraceSummaries',
      'GetTraceSegments',
      'GetTimeSeriesServiceStatistics',
    ],
    parityLevel: 'planned',
    summary: 'Traces, service maps and trace summaries.',
  },
  {
    id: 'cloud9',
    displayName: 'Cloud9',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-cloud9',
    iconKey: 'cloud9',
    operations: ['ListEnvironments', 'DescribeEnvironments', 'CreateEnvironmentEC2'],
    parityLevel: 'planned',
    summary: 'Cloud development environments.',
  },
  {
    id: 'amplify',
    displayName: 'Amplify',
    category: 'Developer Tools',
    sdkPackage: '@aws-sdk/client-amplify',
    iconKey: 'amplify',
    operations: ['ListApps', 'GetApp', 'CreateApp', 'DeleteApp'],
    parityLevel: 'browser',
    summary: 'Front-end apps, branches and deployments.',
    browser: {
      list: { operation: 'ListApps', resultPath: 'apps', idField: 'appId', nameField: 'name' },
      describe: { operation: 'GetApp', idParam: 'appId' },
      delete: { operation: 'DeleteApp', idParam: 'appId' },
    },
  },
] as const satisfies readonly ServiceDescriptor[];
