import type { ServiceDescriptor } from './types.js';

/** Application integration services, in console order. */
export const INTEGRATION_SERVICES = [
  {
    id: 'sqs',
    displayName: 'SQS',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-sqs',
    iconKey: 'sqs',
    operations: [
      'ListQueues',
      'CreateQueue',
      'GetQueueAttributes',
      'GetQueueUrl',
      'SendMessage',
      'ReceiveMessage',
      'DeleteQueue',
    ],
    parityLevel: 'browser',
    summary: 'Queues, attributes, messages and dead-letter redrive.',
    browser: {
      list: { operation: 'ListQueues', resultPath: 'QueueUrls' },
      describe: {
        operation: 'GetQueueAttributes',
        idParam: 'QueueUrl',
        input: { AttributeNames: ['All'] },
      },
      delete: { operation: 'DeleteQueue', idParam: 'QueueUrl' },
    },
  },
  {
    id: 'sns',
    displayName: 'SNS',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-sns',
    iconKey: 'sns',
    operations: [
      'ListTopics',
      'CreateTopic',
      'DeleteTopic',
      'ListSubscriptions',
      'Subscribe',
      'Publish',
      'GetTopicAttributes',
      'ListTagsForResource',
      'TagResource',
      'UntagResource',
    ],
    parityLevel: 'browser',
    summary: 'Topics, subscriptions and message publishing.',
    browser: {
      list: { operation: 'ListTopics', resultPath: 'Topics', idField: 'TopicArn' },
      describe: { operation: 'GetTopicAttributes', idParam: 'TopicArn' },
      delete: { operation: 'DeleteTopic', idParam: 'TopicArn' },
      tags: {
        operation: 'ListTagsForResource',
        idParam: 'ResourceArn',
        resultPath: 'Tags',
      },
    },
  },
  {
    id: 'events',
    displayName: 'EventBridge',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-eventbridge',
    iconKey: 'eventbridge',
    operations: [
      'ListEventBuses',
      'ListRules',
      'PutRule',
      'DeleteRule',
      'PutEvents',
      'ListTargetsByRule',
      'DescribeEventBus',
      'DeleteEventBus',
    ],
    parityLevel: 'browser',
    summary: 'Event buses, rules, targets and matched events.',
    browser: {
      list: {
        operation: 'ListEventBuses',
        resultPath: 'EventBuses',
        idField: 'Arn',
        nameField: 'Name',
      },
      describe: { operation: 'DescribeEventBus', idParam: 'Name' },
      delete: { operation: 'DeleteEventBus', idParam: 'Name' },
    },
  },
  {
    id: 'stepfunctions',
    displayName: 'Step Functions',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-sfn',
    iconKey: 'stepfunctions',
    operations: [
      'ListStateMachines',
      'CreateStateMachine',
      'DescribeStateMachine',
      'StartExecution',
      'DescribeExecution',
      'ListExecutions',
      'DeleteStateMachine',
    ],
    parityLevel: 'browser',
    summary: 'State machines, executions and execution history.',
    browser: {
      list: {
        operation: 'ListStateMachines',
        resultPath: 'stateMachines',
        idField: 'stateMachineArn',
        nameField: 'name',
      },
      describe: { operation: 'DescribeStateMachine', idParam: 'stateMachineArn' },
      delete: { operation: 'DeleteStateMachine', idParam: 'stateMachineArn' },
    },
  },
  {
    id: 'scheduler',
    displayName: 'EventBridge Scheduler',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-scheduler',
    iconKey: 'eventbridge',
    operations: ['ListSchedules', 'CreateSchedule', 'GetSchedule', 'DeleteSchedule'],
    parityLevel: 'browser',
    summary: 'One-time and recurring schedules for AWS API targets.',
    browser: {
      list: { operation: 'ListSchedules', resultPath: 'Schedules', idField: 'Name' },
      describe: { operation: 'GetSchedule', idParam: 'Name' },
      delete: { operation: 'DeleteSchedule', idParam: 'Name' },
    },
  },
  {
    id: 'appsync',
    displayName: 'AppSync',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-appsync',
    iconKey: 'appsync',
    operations: [
      'ListGraphqlApis',
      'CreateGraphqlApi',
      'GetGraphqlApi',
      'ListDataSources',
      'DeleteGraphqlApi',
    ],
    parityLevel: 'browser',
    summary: 'GraphQL APIs, data sources and resolvers.',
    browser: {
      list: {
        operation: 'ListGraphqlApis',
        resultPath: 'graphqlApis',
        idField: 'apiId',
        nameField: 'name',
      },
      describe: { operation: 'GetGraphqlApi', idParam: 'apiId' },
      delete: { operation: 'DeleteGraphqlApi', idParam: 'apiId' },
    },
  },
  {
    id: 'mq',
    displayName: 'Amazon MQ',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-mq',
    iconKey: 'mq',
    operations: ['ListBrokers', 'DescribeBroker', 'CreateBroker', 'ListConfigurations'],
    parityLevel: 'browser',
    summary: 'Managed ActiveMQ and RabbitMQ brokers.',
    browser: {
      list: {
        operation: 'ListBrokers',
        resultPath: 'BrokerSummaries',
        idField: 'BrokerArn',
        nameField: 'BrokerName',
      },
    },
  },
  {
    id: 'swf',
    displayName: 'SWF',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-swf',
    iconKey: 'swf',
    operations: ['ListDomains', 'RegisterDomain', 'DescribeDomain'],
    parityLevel: 'browser',
    summary: 'Simple Workflow domains and workflow executions.',
    browser: {
      list: { operation: 'ListDomains', resultPath: 'domainInfos', idField: 'name' },
      describe: { operation: 'DescribeDomain', idParam: 'name' },
    },
  },
  {
    id: 'pipes',
    displayName: 'EventBridge Pipes',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-pipes',
    iconKey: 'eventbridge',
    operations: ['ListPipes', 'CreatePipe', 'DescribePipe', 'DeletePipe'],
    parityLevel: 'browser',
    summary: 'Point-to-point integrations between event sources and targets.',
    browser: {
      list: { operation: 'ListPipes', resultPath: 'Pipes', idField: 'Name' },
      describe: { operation: 'DescribePipe', idParam: 'Name' },
      delete: { operation: 'DeletePipe', idParam: 'Name' },
    },
  },
  {
    id: 'appconfig',
    displayName: 'AppConfig',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-appconfig',
    iconKey: 'appconfig',
    operations: [
      'ListApplications',
      'CreateApplication',
      'ListEnvironments',
      'ListConfigurationProfiles',
      'GetApplication',
      'DeleteApplication',
    ],
    parityLevel: 'browser',
    summary: 'Feature flags and configuration deployments.',
    healthKeys: ['appconfigdata'],
    browser: {
      list: {
        operation: 'ListApplications',
        resultPath: 'Items',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'GetApplication', idParam: 'ApplicationId' },
      delete: { operation: 'DeleteApplication', idParam: 'ApplicationId' },
    },
  },
  {
    id: 'ses',
    displayName: 'SES',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-sesv2',
    iconKey: 'ses',
    operations: [
      'ListEmailIdentities',
      'CreateEmailIdentity',
      'GetAccount',
      'SendEmail',
      'GetEmailIdentity',
      'DeleteEmailIdentity',
    ],
    parityLevel: 'browser',
    summary: 'Verified sending identities and email sending.',
    healthKeys: ['sesv2'],
    browser: {
      list: {
        operation: 'ListEmailIdentities',
        resultPath: 'EmailIdentities',
        idField: 'IdentityName',
      },
      describe: { operation: 'GetEmailIdentity', idParam: 'EmailIdentity' },
      delete: { operation: 'DeleteEmailIdentity', idParam: 'EmailIdentity' },
    },
  },
  {
    id: 'serverlessrepo',
    displayName: 'Serverless Application Repository',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-serverlessapplicationrepository',
    iconKey: 'serverlessrepo',
    operations: ['ListApplications', 'GetApplication', 'CreateApplication', 'DeleteApplication'],
    parityLevel: 'browser',
    summary: 'Published serverless applications and their versions.',
    browser: {
      list: {
        operation: 'ListApplications',
        resultPath: 'Applications',
        idField: 'ApplicationId',
        nameField: 'Name',
      },
      describe: { operation: 'GetApplication', idParam: 'ApplicationId' },
      delete: { operation: 'DeleteApplication', idParam: 'ApplicationId' },
    },
  },
  {
    id: 'pinpoint',
    displayName: 'Pinpoint',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-pinpoint',
    iconKey: 'pinpoint',
    operations: ['GetApps', 'GetApp', 'CreateApp', 'DeleteApp'],
    parityLevel: 'browser',
    summary: 'Customer engagement applications and campaigns.',
    browser: {
      list: {
        operation: 'GetApps',
        resultPath: 'ApplicationsResponse.Item',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'GetApp', idParam: 'ApplicationId' },
      delete: { operation: 'DeleteApp', idParam: 'ApplicationId' },
    },
  },
  {
    id: 'iot',
    displayName: 'IoT Core',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-iot',
    iconKey: 'iot',
    operations: ['ListThings', 'DescribeThing', 'CreateThing', 'DeleteThing'],
    parityLevel: 'browser',
    summary: 'Connected things, certificates and policies.',
    browser: {
      list: {
        operation: 'ListThings',
        resultPath: 'things',
        idField: 'thingName',
        nameField: 'thingName',
      },
      describe: { operation: 'DescribeThing', idParam: 'thingName' },
      delete: { operation: 'DeleteThing', idParam: 'thingName' },
    },
  },
  {
    id: 'iot-data',
    displayName: 'IoT Data',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-iot-data-plane',
    iconKey: 'iot',
    operations: ['Publish', 'GetThingShadow', 'UpdateThingShadow', 'DeleteThingShadow'],
    parityLevel: 'planned',
    summary: 'Device shadows and MQTT publish over HTTPS.',
  },
  {
    id: 'iotwireless',
    displayName: 'IoT Wireless',
    category: 'Application Integration',
    sdkPackage: '@aws-sdk/client-iot-wireless',
    iconKey: 'iot',
    operations: ['ListDestinations', 'GetDestination', 'CreateDestination', 'DeleteDestination'],
    parityLevel: 'browser',
    summary: 'LoRaWAN and Sidewalk destinations and devices.',
    browser: {
      list: {
        operation: 'ListDestinations',
        resultPath: 'DestinationList',
        idField: 'Arn',
        nameField: 'Name',
      },
      describe: { operation: 'GetDestination', idParam: 'Name' },
      delete: { operation: 'DeleteDestination', idParam: 'Name' },
    },
  },
] as const satisfies readonly ServiceDescriptor[];
