import type { ServiceDescriptor } from './types.js';

/** Machine learning services, in console order. */
export const MACHINE_LEARNING_SERVICES = [
  {
    id: 'sagemaker',
    displayName: 'SageMaker',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-sagemaker',
    iconKey: 'sagemaker',
    operations: [
      'ListEndpoints',
      'DescribeEndpoint',
      'ListNotebookInstances',
      'ListModels',
      'ListTrainingJobs',
      'DeleteEndpoint',
    ],
    parityLevel: 'browser',
    summary: 'Notebooks, models, endpoints and training jobs.',
    healthKeys: ['sagemaker-runtime'],
    browser: {
      list: {
        operation: 'ListEndpoints',
        resultPath: 'Endpoints',
        idField: 'EndpointName',
      },
      describe: { operation: 'DescribeEndpoint', idParam: 'EndpointName' },
      delete: { operation: 'DeleteEndpoint', idParam: 'EndpointName' },
    },
  },
  {
    id: 'bedrock',
    displayName: 'Bedrock',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-bedrock',
    iconKey: 'bedrock',
    operations: ['ListFoundationModels', 'ListGuardrails', 'GetFoundationModel'],
    parityLevel: 'browser',
    summary: 'Foundation models, guardrails and model access.',
    healthKeys: ['bedrock-runtime', 'bedrock-agentcore', 'bedrock-agentcore-control'],
    browser: {
      list: {
        operation: 'ListFoundationModels',
        resultPath: 'modelSummaries',
        idField: 'modelId',
        nameField: 'modelName',
        pagination: { requestField: 'nextToken', responseField: 'nextToken' },
      },
      describe: { operation: 'GetFoundationModel', idParam: 'modelIdentifier' },
    },
  },
  {
    id: 'textract',
    displayName: 'Textract',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-textract',
    iconKey: 'textract',
    operations: ['DetectDocumentText', 'AnalyzeDocument', 'StartDocumentAnalysis'],
    parityLevel: 'planned',
    summary: 'Document text and form extraction.',
  },
  {
    id: 'transcribe',
    displayName: 'Transcribe',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-transcribe',
    iconKey: 'transcribe',
    operations: [
      'ListTranscriptionJobs',
      'StartTranscriptionJob',
      'GetTranscriptionJob',
      'DeleteTranscriptionJob',
    ],
    parityLevel: 'browser',
    summary: 'Speech-to-text transcription jobs.',
    browser: {
      list: {
        operation: 'ListTranscriptionJobs',
        resultPath: 'TranscriptionJobSummaries',
        idField: 'TranscriptionJobName',
      },
      describe: { operation: 'GetTranscriptionJob', idParam: 'TranscriptionJobName' },
      delete: { operation: 'DeleteTranscriptionJob', idParam: 'TranscriptionJobName' },
    },
  },
  {
    id: 'rekognition',
    displayName: 'Rekognition',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-rekognition',
    iconKey: 'rekognition',
    operations: ['ListCollections', 'DetectLabels', 'IndexFaces'],
    parityLevel: 'planned',
    summary: 'Image and video analysis.',
  },
  {
    id: 'comprehend',
    displayName: 'Comprehend',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-comprehend',
    iconKey: 'comprehend',
    operations: ['DetectSentiment', 'DetectEntities', 'ListEntityRecognizers'],
    parityLevel: 'planned',
    summary: 'Natural language processing and entity detection.',
  },
  {
    id: 'translate',
    displayName: 'Translate',
    category: 'Machine Learning',
    sdkPackage: '@aws-sdk/client-translate',
    iconKey: 'translate',
    operations: ['TranslateText', 'ListTerminologies'],
    parityLevel: 'planned',
    summary: 'Machine translation of text.',
  },
] as const satisfies readonly ServiceDescriptor[];
