import type { ServiceDescriptor } from './types.js';

/** Management & governance services, in console order. */
export const MANAGEMENT_SERVICES = [
  {
    id: 'cloudwatch',
    displayName: 'CloudWatch',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cloudwatch',
    iconKey: 'cloudwatch',
    operations: ['ListMetrics', 'GetMetricData', 'PutMetricAlarm', 'DescribeAlarms'],
    parityLevel: 'browser',
    summary: 'Metrics, alarms and dashboards.',
    browser: {
      list: {
        operation: 'ListMetrics',
        resultPath: 'Metrics',
        idField: ['Namespace', 'MetricName'],
        nameField: ['Namespace', 'MetricName'],
      },
    },
  },
  {
    id: 'logs',
    displayName: 'CloudWatch Logs',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cloudwatch-logs',
    iconKey: 'cloudwatch',
    operations: [
      'DescribeLogGroups',
      'CreateLogGroup',
      'DeleteLogGroup',
      'DescribeLogStreams',
      'GetLogEvents',
      'FilterLogEvents',
      'DescribeMetricFilters',
    ],
    parityLevel: 'browser',
    summary: 'Log groups, streams, events and metric filters.',
    browser: {
      list: {
        operation: 'DescribeLogGroups',
        resultPath: 'logGroups',
        idField: 'logGroupName',
      },
      delete: { operation: 'DeleteLogGroup', idParam: 'logGroupName' },
    },
  },
  {
    id: 'cloudformation',
    displayName: 'CloudFormation',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cloudformation',
    iconKey: 'cloudformation',
    operations: [
      'ListStacks',
      'DescribeStacks',
      'CreateStack',
      'DeleteStack',
      'DescribeStackEvents',
      'DescribeStackResources',
      'GetTemplate',
    ],
    parityLevel: 'browser',
    summary: 'Stacks, templates, resources and stack events.',
    browser: {
      list: {
        operation: 'ListStacks',
        resultPath: 'StackSummaries',
        idField: 'StackName',
      },
      describe: { operation: 'DescribeStacks', idParam: 'StackName' },
      delete: { operation: 'DeleteStack', idParam: 'StackName' },
    },
  },
  {
    id: 'ssm',
    displayName: 'Systems Manager',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-ssm',
    iconKey: 'ssm',
    operations: [
      'DescribeParameters',
      'GetParameter',
      'PutParameter',
      'DeleteParameter',
      'GetParametersByPath',
    ],
    parityLevel: 'browser',
    summary: 'Parameter Store hierarchies, documents and commands.',
    browser: {
      list: { operation: 'DescribeParameters', resultPath: 'Parameters', idField: 'Name' },
      describe: { operation: 'GetParameter', idParam: 'Name' },
      delete: { operation: 'DeleteParameter', idParam: 'Name' },
    },
  },
  {
    id: 'cloudtrail',
    displayName: 'CloudTrail',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cloudtrail',
    iconKey: 'cloudtrail',
    operations: ['DescribeTrails', 'GetTrailStatus', 'LookupEvents', 'DeleteTrail'],
    parityLevel: 'browser',
    summary: 'Trails and API activity events.',
    browser: {
      list: { operation: 'DescribeTrails', resultPath: 'trailList', idField: 'Name' },
      describe: {
        operation: 'DescribeTrails',
        idParam: 'trailNameList',
        idParamIsArray: true,
      },
      delete: { operation: 'DeleteTrail', idParam: 'Name' },
    },
  },
  {
    id: 'config',
    displayName: 'Config',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-config-service',
    iconKey: 'config',
    operations: [
      'DescribeConfigRules',
      'DescribeConfigurationRecorders',
      'GetComplianceSummary',
      'DeleteConfigurationRecorder',
    ],
    parityLevel: 'browser',
    summary: 'Resource configuration history, rules and compliance.',
    browser: {
      list: {
        operation: 'DescribeConfigurationRecorders',
        resultPath: 'ConfigurationRecorders',
        idField: 'name',
      },
      describe: {
        operation: 'DescribeConfigurationRecorders',
        idParam: 'ConfigurationRecorderNames',
        idParamIsArray: true,
      },
      delete: {
        operation: 'DeleteConfigurationRecorder',
        idParam: 'ConfigurationRecorderName',
      },
    },
  },
  {
    id: 'organizations',
    displayName: 'Organizations',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-organizations',
    iconKey: 'organizations',
    operations: [
      'DescribeOrganization',
      'ListAccounts',
      'ListOrganizationalUnitsForParent',
      'DescribeAccount',
      'ListRoots',
    ],
    parityLevel: 'browser',
    summary: 'Accounts, organizational units and policies.',
    browser: {
      list: { operation: 'ListAccounts', resultPath: 'Accounts', idField: 'Id', nameField: 'Name' },
      describe: { operation: 'DescribeAccount', idParam: 'AccountId' },
    },
  },
  {
    id: 'ce',
    displayName: 'Cost Explorer',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cost-explorer',
    iconKey: 'ce',
    operations: ['GetCostAndUsage', 'GetDimensionValues', 'GetCostForecast'],
    parityLevel: 'planned',
    summary: 'Cost and usage breakdowns and forecasts.',
  },
  {
    id: 'support',
    displayName: 'Support',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-support',
    iconKey: 'support',
    operations: ['DescribeCases', 'DescribeTrustedAdvisorChecks', 'DescribeSeverityLevels'],
    parityLevel: 'planned',
    summary: 'Support cases and Trusted Advisor checks.',
  },
  {
    id: 'fis',
    displayName: 'Fault Injection Simulator',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-fis',
    iconKey: 'fis',
    operations: [
      'ListExperiments',
      'ListExperimentTemplates',
      'StartExperiment',
      'StopExperiment',
      'GetExperimentTemplate',
      'DeleteExperimentTemplate',
    ],
    parityLevel: 'browser',
    summary: 'Chaos engineering experiment templates and runs.',
    browser: {
      list: {
        operation: 'ListExperimentTemplates',
        resultPath: 'experimentTemplates',
        idField: 'id',
      },
      describe: { operation: 'GetExperimentTemplate', idParam: 'id' },
      delete: { operation: 'DeleteExperimentTemplate', idParam: 'id' },
    },
  },
  {
    id: 'cloudcontrol',
    displayName: 'Cloud Control API',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-cloudcontrol',
    iconKey: 'cloudcontrol',
    operations: ['ListResources', 'GetResource', 'CreateResource', 'DeleteResource'],
    parityLevel: 'planned',
    summary: 'Uniform CRUD over resource types across services.',
  },
  {
    id: 'resourcegroupstaggingapi',
    displayName: 'Resource Groups & Tag Editor',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-resource-groups-tagging-api',
    iconKey: 'tagging',
    operations: ['GetResources', 'GetTagKeys', 'GetTagValues', 'TagResources'],
    parityLevel: 'browser',
    summary: 'Tag-based resource search and bulk tagging.',
    browser: {
      list: {
        operation: 'GetResources',
        resultPath: 'ResourceTagMappingList',
        idField: 'ResourceARN',
        nameField: 'ResourceARN',
      },
    },
  },
  {
    id: 'resource-groups',
    displayName: 'Resource Groups',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-resource-groups',
    iconKey: 'resource-groups',
    operations: ['ListGroups', 'GetGroup', 'CreateGroup', 'DeleteGroup'],
    parityLevel: 'browser',
    summary: 'Tag-based resource groups and their queries.',
    browser: {
      list: {
        operation: 'ListGroups',
        resultPath: 'Groups',
        idField: 'GroupArn',
        nameField: 'GroupName',
      },
      describe: { operation: 'GetGroup', idParam: 'GroupName' },
      delete: { operation: 'DeleteGroup', idParam: 'GroupName' },
    },
  },
  {
    id: 'servicecatalog',
    displayName: 'Service Catalog',
    category: 'Management & Governance',
    sdkPackage: '@aws-sdk/client-service-catalog',
    iconKey: 'servicecatalog',
    operations: ['ListPortfolios', 'ListProducts', 'DescribeProduct'],
    parityLevel: 'planned',
    summary: 'Curated portfolios and provisioned products.',
  },
] as const satisfies readonly ServiceDescriptor[];
