import type { ServiceDescriptor } from './types.js';

/** Networking & CDN services, in console order. */
export const NETWORKING_SERVICES = [
  {
    id: 'cloudfront',
    displayName: 'CloudFront',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-cloudfront',
    iconKey: 'cloudfront',
    operations: ['ListDistributions', 'GetDistribution', 'CreateDistribution', 'ListCachePolicies'],
    parityLevel: 'browser',
    summary: 'Content delivery distributions, origins and cache policies.',
    healthKeys: ['cloudfront-keyvaluestore'],
    browser: {
      list: {
        operation: 'ListDistributions',
        resultPath: 'DistributionList.Items',
        idField: 'Id',
        nameField: 'DomainName',
      },
      describe: { operation: 'GetDistribution', idParam: 'Id' },
    },
  },
  {
    id: 'route53',
    displayName: 'Route 53',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-route-53',
    iconKey: 'route53',
    operations: [
      'ListHostedZones',
      'CreateHostedZone',
      'ListResourceRecordSets',
      'ChangeResourceRecordSets',
      'GetHostedZone',
      'DeleteHostedZone',
    ],
    parityLevel: 'browser',
    summary: 'Hosted zones, record sets and health checks.',
    browser: {
      list: {
        operation: 'ListHostedZones',
        resultPath: 'HostedZones',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'GetHostedZone', idParam: 'Id' },
      delete: { operation: 'DeleteHostedZone', idParam: 'Id' },
    },
  },
  {
    id: 'route53resolver',
    displayName: 'Route 53 Resolver',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-route53resolver',
    iconKey: 'route53',
    operations: [
      'ListResolverEndpoints',
      'ListResolverRules',
      'ListResolverQueryLogConfigs',
      'GetResolverEndpoint',
      'DeleteResolverEndpoint',
    ],
    parityLevel: 'browser',
    summary: 'VPC DNS resolution endpoints and forwarding rules.',
    browser: {
      list: {
        operation: 'ListResolverEndpoints',
        resultPath: 'ResolverEndpoints',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'GetResolverEndpoint', idParam: 'ResolverEndpointId' },
      delete: { operation: 'DeleteResolverEndpoint', idParam: 'ResolverEndpointId' },
    },
  },
  {
    id: 'elbv2',
    displayName: 'Elastic Load Balancing',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-elastic-load-balancing-v2',
    iconKey: 'elbv2',
    operations: [
      'DescribeLoadBalancers',
      'CreateLoadBalancer',
      'DeleteLoadBalancer',
      'DescribeTargetGroups',
      'DescribeListeners',
    ],
    parityLevel: 'browser',
    summary: 'Application, network and gateway load balancers and target groups.',
    healthKeys: ['elb'],
    browser: {
      list: {
        operation: 'DescribeLoadBalancers',
        resultPath: 'LoadBalancers',
        idField: 'LoadBalancerArn',
        nameField: 'LoadBalancerName',
      },
      describe: {
        operation: 'DescribeLoadBalancers',
        idParam: 'LoadBalancerArns',
        idParamIsArray: true,
      },
      delete: { operation: 'DeleteLoadBalancer', idParam: 'LoadBalancerArn' },
    },
  },
  {
    id: 'apigateway',
    displayName: 'API Gateway',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-api-gateway',
    iconKey: 'apigateway',
    operations: [
      'GetRestApis',
      'CreateRestApi',
      'DeleteRestApi',
      'GetResources',
      'GetStages',
      'CreateDeployment',
      'GetRestApi',
    ],
    parityLevel: 'browser',
    summary: 'REST APIs, resources, methods, stages and deployments.',
    healthKeys: ['apigatewayv2', 'apigatewaymanagementapi'],
    browser: {
      list: { operation: 'GetRestApis', resultPath: 'items', idField: 'id', nameField: 'name' },
      describe: { operation: 'GetRestApi', idParam: 'restApiId' },
      delete: { operation: 'DeleteRestApi', idParam: 'restApiId' },
    },
  },
  {
    id: 'servicediscovery',
    displayName: 'Cloud Map',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-servicediscovery',
    iconKey: 'servicediscovery',
    operations: [
      'ListNamespaces',
      'ListServices',
      'ListInstances',
      'GetNamespace',
      'DeleteNamespace',
    ],
    parityLevel: 'browser',
    summary: 'Service namespaces and instance discovery.',
    browser: {
      list: {
        operation: 'ListNamespaces',
        resultPath: 'Namespaces',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'GetNamespace', idParam: 'Id' },
      delete: { operation: 'DeleteNamespace', idParam: 'Id' },
    },
  },
  {
    id: 'globalaccelerator',
    displayName: 'Global Accelerator',
    category: 'Networking & CDN',
    sdkPackage: '@aws-sdk/client-global-accelerator',
    iconKey: 'globalaccelerator',
    operations: [
      'ListAccelerators',
      'ListListeners',
      'ListEndpointGroups',
      'DescribeAccelerator',
      'DeleteAccelerator',
    ],
    parityLevel: 'browser',
    summary: 'Anycast accelerators for global traffic routing.',
    browser: {
      list: {
        operation: 'ListAccelerators',
        resultPath: 'Accelerators',
        idField: 'AcceleratorArn',
        nameField: 'Name',
      },
      describe: { operation: 'DescribeAccelerator', idParam: 'AcceleratorArn' },
      delete: { operation: 'DeleteAccelerator', idParam: 'AcceleratorArn' },
    },
  },
] as const satisfies readonly ServiceDescriptor[];
