import type { ServiceDescriptor } from './types.js';

/** Security, identity and compliance services, in console order. */
export const SECURITY_SERVICES = [
  {
    id: 'sts',
    displayName: 'STS',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-sts',
    iconKey: 'sts',
    operations: ['GetCallerIdentity', 'AssumeRole', 'GetSessionToken', 'GetAccessKeyInfo'],
    parityLevel: 'planned',
    summary: 'Caller identity and temporary security credentials.',
  },
  {
    id: 'iam',
    displayName: 'IAM',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-iam',
    iconKey: 'iam',
    operations: [
      // Users
      'ListUsers',
      'CreateUser',
      'GetUser',
      'DeleteUser',
      'ListUserTags',
      'TagUser',
      'UntagUser',
      // Access keys
      'ListAccessKeys',
      'CreateAccessKey',
      'UpdateAccessKey',
      'DeleteAccessKey',
      // Groups
      'ListGroups',
      'CreateGroup',
      'GetGroup',
      'DeleteGroup',
      'AddUserToGroup',
      'RemoveUserFromGroup',
      'ListGroupsForUser',
      // Roles
      'ListRoles',
      'CreateRole',
      'GetRole',
      'DeleteRole',
      'UpdateAssumeRolePolicy',
      'ListRoleTags',
      'TagRole',
      'UntagRole',
      // Policies
      'ListPolicies',
      'CreatePolicy',
      'GetPolicy',
      'DeletePolicy',
      'GetPolicyVersion',
      'CreatePolicyVersion',
      'ListPolicyVersions',
      'DeletePolicyVersion',
      'ListEntitiesForPolicy',
      // Attached policies
      'ListAttachedUserPolicies',
      'AttachUserPolicy',
      'DetachUserPolicy',
      'ListAttachedGroupPolicies',
      'AttachGroupPolicy',
      'DetachGroupPolicy',
      'ListAttachedRolePolicies',
      'AttachRolePolicy',
      'DetachRolePolicy',
    ],
    parityLevel: 'dedicated',
    summary: 'Users, groups, roles, policies and access keys.',
    browser: {
      list: {
        operation: 'ListUsers',
        resultPath: 'Users',
        idField: 'UserName',
        pagination: { requestField: 'Marker', responseField: 'Marker' },
      },
      describe: { operation: 'GetUser', idParam: 'UserName' },
      delete: { operation: 'DeleteUser', idParam: 'UserName' },
      tags: { operation: 'ListUserTags', idParam: 'UserName', resultPath: 'Tags' },
    },
  },
  {
    id: 'kms',
    displayName: 'KMS',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-kms',
    iconKey: 'kms',
    operations: ['ListKeys', 'DescribeKey', 'CreateKey', 'ListAliases', 'EnableKeyRotation'],
    parityLevel: 'browser',
    summary: 'Customer managed keys, aliases and rotation.',
    browser: {
      list: {
        operation: 'ListKeys',
        resultPath: 'Keys',
        idField: 'KeyId',
        pagination: { requestField: 'Marker', responseField: 'NextMarker' },
      },
      describe: { operation: 'DescribeKey', idParam: 'KeyId' },
    },
  },
  {
    id: 'secretsmanager',
    displayName: 'Secrets Manager',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-secrets-manager',
    iconKey: 'secretsmanager',
    operations: [
      'ListSecrets',
      'DescribeSecret',
      'CreateSecret',
      'GetSecretValue',
      'PutSecretValue',
      'DeleteSecret',
    ],
    parityLevel: 'browser',
    summary: 'Secret values, versions and rotation configuration.',
    browser: {
      list: {
        operation: 'ListSecrets',
        resultPath: 'SecretList',
        idField: 'ARN',
        nameField: 'Name',
      },
      describe: { operation: 'DescribeSecret', idParam: 'SecretId' },
      delete: { operation: 'DeleteSecret', idParam: 'SecretId' },
    },
  },
  {
    id: 'acm',
    displayName: 'Certificate Manager',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-acm',
    iconKey: 'acm',
    operations: [
      'ListCertificates',
      'RequestCertificate',
      'DescribeCertificate',
      'DeleteCertificate',
    ],
    parityLevel: 'browser',
    summary: 'Public and private TLS certificates.',
    browser: {
      list: {
        operation: 'ListCertificates',
        resultPath: 'CertificateSummaryList',
        idField: 'CertificateArn',
        nameField: 'DomainName',
      },
      describe: { operation: 'DescribeCertificate', idParam: 'CertificateArn' },
      delete: { operation: 'DeleteCertificate', idParam: 'CertificateArn' },
    },
  },
  {
    id: 'acm-pca',
    displayName: 'Private CA',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-acm-pca',
    iconKey: 'acm',
    operations: [
      'ListCertificateAuthorities',
      'CreateCertificateAuthority',
      'GetCertificate',
      'DescribeCertificateAuthority',
      'DeleteCertificateAuthority',
    ],
    parityLevel: 'browser',
    summary: 'Private certificate authorities and issued certificates.',
    browser: {
      list: {
        operation: 'ListCertificateAuthorities',
        resultPath: 'CertificateAuthorities',
        idField: 'Arn',
        nameField: 'CertificateAuthorityConfiguration.Subject.CommonName',
      },
      describe: { operation: 'DescribeCertificateAuthority', idParam: 'CertificateAuthorityArn' },
      delete: { operation: 'DeleteCertificateAuthority', idParam: 'CertificateAuthorityArn' },
    },
  },
  {
    id: 'cognito-idp',
    displayName: 'Cognito',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-cognito-identity-provider',
    iconKey: 'cognito',
    operations: [
      'ListUserPools',
      'CreateUserPool',
      'DescribeUserPool',
      'ListUserPoolClients',
      'ListUsers',
      'DeleteUserPool',
    ],
    parityLevel: 'browser',
    summary: 'User pools, app clients and identity pools.',
    healthKeys: ['cognito-identity'],
    browser: {
      list: {
        operation: 'ListUserPools',
        resultPath: 'UserPools',
        idField: 'Id',
        nameField: 'Name',
      },
      describe: { operation: 'DescribeUserPool', idParam: 'UserPoolId' },
      delete: { operation: 'DeleteUserPool', idParam: 'UserPoolId' },
    },
  },
  {
    id: 'wafv2',
    displayName: 'WAF',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-wafv2',
    iconKey: 'wafv2',
    operations: ['ListWebACLs', 'CreateWebACL', 'ListRuleGroups', 'AssociateWebACL'],
    parityLevel: 'browser',
    summary: 'Web ACLs, rule groups and IP sets.',
    browser: {
      list: {
        operation: 'ListWebACLs',
        input: { Scope: 'REGIONAL' },
        resultPath: 'WebACLs',
        idField: 'Id',
        nameField: 'Name',
        // WAFv2 paginates with `NextMarker` in both directions.
        pagination: { requestField: 'NextMarker', responseField: 'NextMarker' },
      },
    },
  },
  {
    id: 'shield',
    displayName: 'Shield',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-shield',
    iconKey: 'shield',
    operations: ['ListProtections', 'CreateProtection', 'DescribeProtection'],
    parityLevel: 'planned',
    summary: 'DDoS protection for accelerated and edge resources.',
  },
  {
    id: 'verifiedpermissions',
    displayName: 'Verified Permissions',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-verifiedpermissions',
    iconKey: 'verifiedpermissions',
    operations: [
      'ListPolicyStores',
      'CreatePolicyStore',
      'ListPolicies',
      'ListIdentitySources',
      'GetPolicyStore',
      'DeletePolicyStore',
    ],
    parityLevel: 'browser',
    summary: 'Cedar policy stores and authorization decisions.',
    browser: {
      list: {
        operation: 'ListPolicyStores',
        resultPath: 'policyStores',
        idField: 'policyStoreId',
        pagination: { requestField: 'nextToken', responseField: 'nextToken' },
      },
      describe: { operation: 'GetPolicyStore', idParam: 'policyStoreId' },
      delete: { operation: 'DeletePolicyStore', idParam: 'policyStoreId' },
    },
  },
  {
    id: 'guardduty',
    displayName: 'GuardDuty',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-guardduty',
    iconKey: 'guardduty',
    operations: ['ListDetectors', 'CreateDetector', 'ListFindings'],
    parityLevel: 'planned',
    summary: 'Threat detection findings and detectors.',
  },
  {
    id: 'inspector',
    displayName: 'Inspector',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-inspector2',
    iconKey: 'inspector',
    operations: ['ListFindings', 'ListCoverage', 'BatchGetAccountStatus'],
    parityLevel: 'planned',
    summary: 'Vulnerability findings for EC2, ECR and Lambda.',
  },
  {
    id: 'identitystore',
    displayName: 'Identity Store',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-identitystore',
    iconKey: 'cognito',
    operations: ['ListUsers', 'DescribeUser', 'ListGroups', 'DescribeGroup'],
    parityLevel: 'planned',
    summary: 'Users and groups inside IAM Identity Center stores.',
  },
  {
    id: 'sso-admin',
    displayName: 'IAM Identity Center',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-sso-admin',
    iconKey: 'sso-admin',
    operations: ['ListInstances', 'DescribeInstance', 'CreateInstance', 'DeleteInstance'],
    parityLevel: 'browser',
    summary: 'IAM Identity Center instances and permission sets.',
    browser: {
      list: {
        operation: 'ListInstances',
        resultPath: 'Instances',
        idField: 'InstanceArn',
      },
      describe: { operation: 'DescribeInstance', idParam: 'InstanceArn' },
      delete: { operation: 'DeleteInstance', idParam: 'InstanceArn' },
    },
  },
  {
    id: 'ram',
    displayName: 'Resource Access Manager',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-ram',
    iconKey: 'ram',
    operations: ['ListResources', 'ListPrincipals', 'ListResourceShares'],
    parityLevel: 'planned',
    summary: 'Resource shares across accounts and organizational units.',
  },
  {
    id: 'account',
    displayName: 'Account Management',
    category: 'Security Identity & Compliance',
    sdkPackage: '@aws-sdk/client-account',
    iconKey: 'account',
    operations: ['ListRegions', 'GetRegionOptStatus', 'EnableRegion', 'GetAccountInformation'],
    parityLevel: 'planned',
    summary: 'Account details and enabled AWS Regions.',
  },
] as const satisfies readonly ServiceDescriptor[];
