import type { ServiceDescriptor } from './types.js';

/** Storage services, in console order. */
export const STORAGE_SERVICES = [
  {
    id: 's3',
    displayName: 'S3',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-s3',
    iconKey: 's3',
    operations: [
      // Buckets
      'ListBuckets',
      'CreateBucket',
      'DeleteBucket',
      'GetBucketLocation',
      'HeadBucket',
      // Objects
      'ListObjectsV2',
      'GetObject',
      'PutObject',
      'HeadObject',
      'DeleteObject',
      'DeleteObjects',
      'CopyObject',
      // Multipart upload (used by the api's upload proxy for large files)
      'CreateMultipartUpload',
      'UploadPart',
      'CompleteMultipartUpload',
      'AbortMultipartUpload',
      // Versioning
      'GetBucketVersioning',
      'PutBucketVersioning',
      // Tags
      'GetBucketTagging',
      'PutBucketTagging',
      'DeleteBucketTagging',
      // Permissions
      'GetBucketPolicy',
      'PutBucketPolicy',
      'DeleteBucketPolicy',
      'GetPublicAccessBlock',
      'PutPublicAccessBlock',
      'DeletePublicAccessBlock',
      // Encryption
      'GetBucketEncryption',
    ],
    parityLevel: 'dedicated',
    summary: 'Buckets, objects, prefixes, versioning and access points.',
    browser: {
      list: {
        operation: 'ListBuckets',
        resultPath: 'Buckets',
        idField: 'Name',
        pagination: { requestField: 'ContinuationToken', responseField: 'ContinuationToken' },
      },
      describe: { operation: 'HeadBucket', idParam: 'Bucket' },
      delete: { operation: 'DeleteBucket', idParam: 'Bucket' },
      tags: { operation: 'GetBucketTagging', idParam: 'Bucket', resultPath: 'TagSet' },
    },
  },
  {
    id: 's3control',
    displayName: 'S3 Control',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-s3-control',
    iconKey: 's3',
    operations: ['ListAccessPoints', 'GetAccessPoint', 'ListJobs'],
    parityLevel: 'planned',
    summary: 'Account-level S3 settings, access points and batch jobs.',
  },
  {
    id: 's3tables',
    displayName: 'S3 Tables',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-s3tables',
    iconKey: 's3',
    operations: [
      'ListTableBuckets',
      'GetTableBucket',
      'CreateTableBucket',
      'DeleteTableBucket',
      'ListTables',
    ],
    parityLevel: 'browser',
    summary: 'Iceberg table buckets and their tables.',
    browser: {
      list: {
        operation: 'ListTableBuckets',
        resultPath: 'tableBuckets',
        idField: 'arn',
        nameField: 'name',
        pagination: { requestField: 'continuationToken', responseField: 'continuationToken' },
      },
      describe: { operation: 'GetTableBucket', idParam: 'tableBucketARN' },
      delete: { operation: 'DeleteTableBucket', idParam: 'tableBucketARN' },
    },
  },
  {
    id: 'efs',
    displayName: 'EFS',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-efs',
    iconKey: 'efs',
    operations: [
      'DescribeFileSystems',
      'CreateFileSystem',
      'DeleteFileSystem',
      'DescribeMountTargets',
    ],
    parityLevel: 'browser',
    summary: 'Elastic network file systems and mount targets.',
    browser: {
      list: {
        operation: 'DescribeFileSystems',
        resultPath: 'FileSystems',
        idField: 'FileSystemId',
        pagination: { requestField: 'Marker', responseField: 'NextMarker' },
      },
      describe: { operation: 'DescribeFileSystems', idParam: 'FileSystemId' },
      delete: { operation: 'DeleteFileSystem', idParam: 'FileSystemId' },
    },
  },
  {
    id: 'backup',
    displayName: 'Backup',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-backup',
    iconKey: 'backup',
    operations: [
      'ListBackupVaults',
      'ListBackupPlans',
      'StartBackupJob',
      'ListBackupJobs',
      'DescribeBackupVault',
      'DeleteBackupVault',
    ],
    parityLevel: 'browser',
    summary: 'Backup vaults, plans and on-demand backup jobs.',
    browser: {
      list: {
        operation: 'ListBackupVaults',
        resultPath: 'BackupVaultList',
        idField: 'BackupVaultName',
      },
      describe: { operation: 'DescribeBackupVault', idParam: 'BackupVaultName' },
      delete: { operation: 'DeleteBackupVault', idParam: 'BackupVaultName' },
    },
  },
  {
    id: 'glacier',
    displayName: 'S3 Glacier',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-glacier',
    iconKey: 'glacier',
    operations: ['ListVaults', 'CreateVault', 'DeleteVault', 'DescribeVault'],
    parityLevel: 'browser',
    summary: 'Long-term archive vaults and archive retrieval.',
    browser: {
      list: {
        operation: 'ListVaults',
        resultPath: 'VaultList',
        idField: 'VaultName',
        // Glacier's JSON API uses a lowercase request marker and returns `Marker`.
        pagination: { requestField: 'marker', responseField: 'Marker' },
      },
    },
  },
  {
    id: 'transfer',
    displayName: 'Transfer Family',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-transfer',
    iconKey: 'transfer',
    operations: ['ListServers', 'DescribeServer', 'ListUsers', 'DeleteServer'],
    parityLevel: 'browser',
    summary: 'SFTP, FTPS and FTP endpoints backed by S3 or EFS.',
    browser: {
      list: { operation: 'ListServers', resultPath: 'Servers', idField: 'ServerId' },
      describe: { operation: 'DescribeServer', idParam: 'ServerId' },
      delete: { operation: 'DeleteServer', idParam: 'ServerId' },
    },
  },
  {
    id: 'fsx',
    displayName: 'FSx',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-fsx',
    iconKey: 'fsx',
    operations: ['DescribeFileSystems', 'CreateFileSystem', 'DeleteFileSystem'],
    parityLevel: 'planned',
    summary: 'Managed Windows, Lustre, ONTAP and OpenZFS file systems.',
  },
  {
    id: 'storagegateway',
    displayName: 'Storage Gateway',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-storage-gateway',
    iconKey: 'storagegateway',
    operations: ['ListGateways', 'DescribeGatewayInformation', 'ListVolumes'],
    parityLevel: 'planned',
    summary: 'Hybrid file, volume and tape gateways.',
  },
  {
    id: 'datasync',
    displayName: 'DataSync',
    category: 'Storage',
    sdkPackage: '@aws-sdk/client-datasync',
    iconKey: 'datasync',
    operations: ['ListTasks', 'DescribeTask', 'StartTaskExecution', 'DeleteTask'],
    parityLevel: 'browser',
    summary: 'Scheduled data movement between storage services.',
    browser: {
      list: {
        operation: 'ListTasks',
        resultPath: 'Tasks',
        idField: 'TaskArn',
        nameField: 'Name',
      },
      describe: { operation: 'DescribeTask', idParam: 'TaskArn' },
      delete: { operation: 'DeleteTask', idParam: 'TaskArn' },
    },
  },
] as const satisfies readonly ServiceDescriptor[];
